openapi: 3.0.3
info:
  title: Courses API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  /courses:
    get:
      summary: Get all courses (ADMIN, TEACHER)
      tags: [Courses]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    post:
      summary: Create new course (ADMIN only)
      tags: [Courses]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseDTO"
            example:
              name: "Mathematics"
      responses:
        '200':
          description: Created course
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /courses/{id}:
    get:
      summary: Get course by ID (ADMIN, TEACHER)
      tags: [Courses]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 3
      responses:
        '200':
          description: Course
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Course not found

    put:
      summary: Update course (ADMIN only)
      tags: [Courses]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseDTO"
            example:
              name: "Mathematics"
      responses:
        '200':
          description: Course updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Course not found

    delete:
      summary: Delete course (ADMIN only)
      tags: [Courses]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 3
      responses:
        '200':
          description: Deleted course
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Course not found

components:
  schemas:

    Course:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Mathematics"

    CourseDTO:
      type: object
      required: [name]
      properties:
        name:
          type: string
          example: "Mathematics"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
