openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  /users/register:
    post:
      summary: Register a new user (ADMIN/manual)
      tags: [Users]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
            example:
              username: "admin.user"
              password: "parolaPuternica"
              role: "ADMIN"
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Validation error
        '401':
          description: Unauthorized

  /users/register-code:
    post:
      summary: Register a new user using registration code (Teacher/Student/Parent)
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterWithCodeRequest"
            example:
              username: "maria.ionescu"
              password: "parolaPuternica"
              registrationCode: "PROF-XYZ99"
      responses:
        '200':
          description: User created and linked to entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Validation error
        '401':
          description: Unauthorized

components:
  schemas:

    RegisterRequest:
      type: object
      required: [username, password, role]
      properties:
        username:
          type: string
          example: "maria.ionescu"
        password:
          type: string
          example: "parolaPuternica"
        role:
          type: string
          enum: [STUDENT, TEACHER, ADMIN, PARENT]
          example: "TEACHER"

    RegisterWithCodeRequest:
      type: object
      required: [username, password, registrationCode]
      properties:
        username:
          type: string
          example: "maria.ionescu"
        password:
          type: string
          example: "parolaPuternica"
        registrationCode:
          type: string
          example: "PROF-XYZ99"

    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "maria.ionescu"
        role:
          type: string
          enum: [STUDENT, TEACHER, ADMIN, PARENT]
          example: "ADMIN"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
